### ISSUE TITLE
Hi,

### ISSUE THREAD

**Issue by Oliver0804** [ustccw/IoTivityESP32#1]
Are you using the official LUBUNTU?

**Comment by ustccw** [comment]
@Oliver0804 sorry for that. i am using the ubuntu16.04.
but we still support windows environment.
you can download the compile toolchain by following the guide
[esp-idf/docs/get-started/windows-setup.rst](https://github.com/espressif/esp-idf/blob/master/docs/get-started/windows-setup.rst)

**Comment by Oliver0804** [comment]
@ustccw Thank you for taking the time to answer
Because I use ESP recommended development environment (lubuntu)
make official example is very good
But an error occurred while making iotivity
![image](https://user-images.githubusercontent.com/8245980/33763867-0d026636-dc4d-11e7-8db0-bab7ae8ea3ec.png)

**Comment by ustccw** [comment]
@Oliver0804 hi, maybe you didnot clone the total repo, try the following command:
```
git submodule update --init --recursive
```

**Comment by Oliver0804** [comment]
thank you very much
I replaced ubuntu try again
And this time there is use --recursive
The problem has been solved

**Comment by Oliver0804** [comment]
I want to control the LEDs on the ESP32 board with iotivity
Is there a recommended practice?

**Comment by ustccw** [comment]
@Oliver0804 glad to hear that your problem has  been solved.
and about the LEDs, we had some demos which can control LEDs on the ESP32,and we now support iotivity.
maybe just do a bit of work to meld two features. 

Best regards

**Comment by Oliver0804** [comment]
I completed the server & client.
but i not see LED the blink.

What steps did I miss?
Which one LED in Blink at GPIO?

![image](https://user-images.githubusercontent.com/8245980/33814753-675307dc-de67-11e7-9d2b-f6314ec246d6.png)

**Comment by ustccw** [comment]
@Oliver0804 glad to see u had run the demo.
about GPIO and LED, you can lookup the [official document](http://espressif.com/en/support/download/documents).
maybe there would be something you need.

**Comment by Oliver0804** [comment]
@ustccw Hi,
Because I see
Part 4: Result shows there to describe
"you would see that light state is changing between esp32 client and esp32 server."
But my ESP32 did not happen, on which GPIO it should happen

**Comment by Oliver0804** [comment]
I find in the main.c (server_freertos.c and client_freertos.c) GPIO configuration
But did not see the relevant information

**Comment by ustccw** [comment]
Hi, just now, i tested the demo again, it worked well as the following:
![_001](https://user-images.githubusercontent.com/24221485/33937211-897612f0-e03d-11e7-9dbb-1e259684071a.png)
maybe you need to roll back your ESP-IDF version to a old commit. 
try the command:
```
git reset --hard 7d86f167ee26f4a8b74decdd968586b87604eeda
```
and still need to setup your compiler environment according the `esp-idf/docs/get-started/linux-setup.rst` if you encounter a compiler error.
good luck.

**Comment by ustccw** [comment]
@Oliver0804 tbh, the demo just show you a software blink rather than a hardware blink with LED.
best regards

**Comment by Oliver0804** [comment]
Thank you very much, I will try your suggestion,
I found that your ESP32 has feedback similar to "GET_light:",
But I do not have the same situation, I will try again

**Comment by Oliver0804** [comment]
My ESP32 only feedback
"iotivityclient: tick_per_ms: 10 & 1512963177" and
"iotivityserver: tick_per_ms: 10 & 1512963020"
After no word,
It may be caused by the IDF problem

**Comment by Oliver0804** [comment]
I use the "git submodule update - init --recursive", use make clean & remake feedback the following message：
![image](https://user-images.githubusercontent.com/8245980/33945991-84a3d1a4-e05b-11e7-8c2d-03928a4b5e90.png)

**Comment by ustccw** [comment]
@Oliver0804 try the following command:
```
make clean && make defconfig && make flash
```

**Comment by Oliver0804** [comment]
@ustccw 
I found that a version of IDF may cause this problem
When I use lubuntu on another computer
The IDF version is 3.1-dev
It does not blink, but run IDF3.0-dev on this computer now
blink is worked.

**Comment by Oliver0804** [comment]
I try to find out the problem on the Server,
I found that I will stay in mutex_lock (& m_cv);
Your ESP32 will print a message on the IDF version?
Can you tell me your version?
![screenshot from 2017-12-18 15-27-07](https://user-images.githubusercontent.com/8245980/34094804-bcfabbd8-e409-11e7-8620-54e5858423ab.png)

**Comment by ustccw** [comment]
@Oliver0804 a version can work this demo in my workspace, `ESP-IDF v3.0-dev-187-g7d86f16`, last commitID:`466323601fec7c9b4fbbd5639abd8a37f1e39952`  , u can have a try.  

and maybe there are some incompatible updates in latest ESP-IDF leads to the problem.  
sorry that i am busying on other things. i would notify you if fixed it up some weeks later.  
plz let me know if you are interested in it and fixed it. tks.

**Comment by Oliver0804** [comment]
@ustccw 
Thank you
I will try to fix it

**Comment by Oliver0804** [comment]
@ustccw I can not find it in the esp-idf commit

**Comment by ustccw** [comment]
@Oliver0804 maybe i didnot clarify the version. you can lookup the following version:

**ESP-IDF version**  

![p1](https://user-images.githubusercontent.com/24221485/34100489-8c157eae-e41d-11e7-9604-0925c0c348fe.png)
------------------------------------------------
------------------------------------------------
**IoTiviryESP32 version**

![p2](https://user-images.githubusercontent.com/24221485/34100544-b7cb9e66-e41d-11e7-81e0-e350feba34ac.png)

**Comment by ustccw** [comment]
@Oliver0804 the demo would work well under the aboving version that picture shows.

but cannot work in the latest ESP-IDF version.

**Comment by ustccw** [comment]
@Oliver0804 hi, i invite u to develop this repo.
if problem was solved, plz new a merge request, tks!
