### ISSUE TITLE
make issue.

### ISSUE THREAD

**Issue by Oliver0804** [ustccw/IoTivityESP32#2]
make[1]: *** No rule to make target 'iotivity-constrained/deps/tinycbor/src/cborencoder.o', needed by 'libiotivity.a'。 停止。

**Comment by ustccw** [comment]
@Oliver0804 hi, you should clone the total repo by 
```
git clone --recursive git@github.com:ustccw/IoTivityESP32.git
```

**Comment by Oliver0804** [comment]
Thank you.
